### ISSUE TITLE
Is it possible to run E2E test when merging to develop branch and not other branches (e.g feature branches etc...)?

### ISSUE THREAD

**Issue by yu-smc** [t29mato/starry-digitizer#211]
## As-Is
E2E tests run only when a new release is created (i.e., when the Vercel Production Build runs).

## To-Be
In addition to the production build, E2E tests should run when merging into the remote develop branch, but not into other branches.

## Detail
In the past, I proposed removing E2E tests from the GitHub workflow for the Vercel preview build in [this issue](https://github.com/t29mato/starry-digitizer/issues/101)
and Mato san changed the workflow settings accordingly.

As mentioned in the conversation within the issue, it is sufficient to run E2E tests only when merging into the develop branch and when releasing to production.

However, currently, the CI triggered by merging into the develop branch is a Preview Build, so E2E tests are not executed.

So, what I would like to ask is: Is it possible to add E2E tests in the GitHub workflow for the Vercel Preview Build, but only when merging into the develop branch?

*Even in the current state, if the E2E test fails during the production release, the deployment will stop, so it is not an urgent matter.

**Comment by t29mato** [comment]
I considered several strategies

**Push Triggers:**
1. **develop:** If an E2E test error occurs, creating another PR is necessary, which is inconvenient.
2. **release:** If an E2E test error occurs, it's easy to commit directly to the release branch.
3. **main:** If an E2E test error occurs, creating another PR is necessary, which is inconvenient.

**Pull Request Triggers:**

4. **to develop:** Running E2E tests on every PR to the develop branch can be problematic due to the test limit, so this is not suitable.
5. **to release:** Fixing errors would require a PR to the develop branch, which is inconvenient.
6. **to main:** Allows direct fixes on the release or hotfix branch if an error occurs.

Initially, option 2 seemed best, but considering the hotfix branch, I decided on option 6.


This is PR https://github.com/t29mato/starry-digitizer/pull/212
